language: minimal

services: docker

install:
  - docker-compose -f deployment/docker/docker-compose-build.yaml build --parallel
deploy:
  - provider: script
    script: bash deployment/docker/publish.sh
    on:
      branch: main